package:
  name: tbb
  version: "4.4_20160128"

source:
  fn: tbb44_20160128oss_osx.tgz  # [osx]
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/mac/tbb44_20160128oss_osx.tgz  # [osx]
  fn: tbb44_20160128oss_src_0.tgz  # [linux]
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20160128oss_src_0.tgz  # [linux]

about:
  home: https://www.threadingbuildingblocks.org/
  license: GPLv2
